### ISSUE TITLE
Week 19 Sept - 25 Sept

### ISSUE THREAD

**Issue by octref** [octref/vscode#2]
- [x] Draft a rough API

**Comment by octref** [comment]
@Tyriar
Feel free to add any tasks.

**Comment by Tyriar** [comment]
- [ ] Create initial version of API - look through `vscode.d.ts` for how other API points represent trees, click handlers, update dynamic items, etc.
- [ ] Implement `window.createViewlet`
  - Allow title to be set
- [ ] Implement creating a tree via the extension API
- [ ] Allow tree to be updated
- [ ] Fire click handlers

**Comment by octref** [comment]
@Tyriar 

Per today's discussion, here is the design I came up with:

- Extension specifies a contribution for its Viewlet
- Extension specifies location of its `TreeContentProvider` (file location and class name)
- Icon get added to activity bar at startup. Not rendering Viewlet yet.
- When Activity Bar icon gets clicked, Viewlet gets rendered. `TreeContentProvider` get instantiated.

`ITreeContentProvider` roughly looks like this:

```ts
interface ITreeContentProvider {
  tree: ITree;

  // Pre-defined events
  onActiveDocumentChanged?: (documentURI: URI, refresh: () => any) => any;
  onActiveDocumentSaved?: (documentURI: URI, refresh: () => any) => any;

  // For other events the extension is interested in
  onData: (data: Object, refresh: () => any ) => any;
}
```

Common usage would be:

-  Something like Outline View which reacts to `activeDocumentChanged`

```ts
class TreeContentProvider implements ITreeContentProvider {
  private _tree: ITree;

  get tree() { return this._tree; }

  onActiveDocumentChanged(documentURI: URI, refresh: () => any): any {
    this._tree = generateOutlineTreeFromDoc(documentURI);
    refresh();
  }
}
```

- Something like DB View which reacts to user-defined events
```ts
class TreeContentProvider implements ITreeContentProvider {
  private _tree: ITree;

  get tree() { return this._tree; }

  onData({ nodeId: number, treeNode: ITreeNode }, refresh): any {
    if (nodeId) {
      this._tree.replaceNodeWith(nodeId, treeNode);
    } else {
      this._tree.root = treeNode;
    }
    refresh();
  }
}
```

Then in `extension.ts`, you'd do:

```ts
import sql from 'sql';
const mydb = new sql(...);

export function activate(context: vscode.ExtensionContext) {
  mydb.onChange((data) => {
    // Some computation and logic
    if (updateWholeTree) {
      vscode.window.updateViewlet(viewletId, { treeNode });
    } else {
      // Only update a specific node
      vscode.window.updateViewlet(viewletId, { nodeId, treeNode })
    }
  });
}
```

**Comment by octref** [comment]
Something I'm not sure is whether to make `ITree` generic, and for each `ITree<T>` make sure it has `getId`, `getLabel`, etc. Similar to how the current `FileDataSource` is working: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L54-L131

**Comment by Tyriar** [comment]
@octref what is `T`?

**Comment by octref** [comment]
The generic type for each node.

**Comment by Tyriar** [comment]
What are examples of what it could store apart from strings? What functions would you type with `T`?

**Comment by octref** [comment]
I'm thinking an interface which implements a subset of `FileStat` for a tree structure (addChild, removeChild, hasChild, etc): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerViewModel.ts

Plus a `toString` or `getLabel`.

Will use it to construct a `IDataSource`, similar to `FileDataSource` here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts

**Comment by Tyriar** [comment]
Did you think about some custom schema and document provider system, so you register something to handle`some-schema://` and any URIs loaded by that are handled by that document provider?

**Comment by octref** [comment]
I did consider it. That's another option we can go for. But if we were to limit the actions to schemas we define, we have to implement each schema by ourselves, and we might need to expand it to cope up with feature-requests. Second, it limits what extension authors could do, and that's an unnecessary limit imo.

Imagine an Outline View where author want to fold/unfold a part of code on double-click. For schemaless design, the user can call vscode API to do what he wants, for schema, we have to implement yet another function.

**Comment by octref** [comment]
Kai also mentioned another use-case: a File Browser for your gist. If you were to access private gists you need to add a token as a POST param. We can have schema for previewHTML, open in external browser, but for POST do we add yet another schema? Better to let extension author use `request` or whatever node module to make the request and open it in editor.

**Comment by Tyriar** [comment]
The way it would work is that the user would click the item, which requests `gist-ext://foo/bar`, this is then handled by the document handler the extension author created and they send the request as appropriate.

**Comment by octref** [comment]
Is there any other part in VSCode that already use such a schema?

This opens up for inter-extension action and a schema to maintain. I'm wondering what would the benefit of this design be.
